import * as CryptoJS from 'crypto-js';
import {
  decrypt,
  DecryptionError,
  encrypt,
  EncryptionSession,
  isEncryptedValue,
  isV2Ciphertext,
} from './cryptic';

describe('cryptic (CrypticService v2 port)', () => {
  describe('golden vectors — locked format compatibility', () => {
    // These were generated by running the exact algorithm documented in
    // cryptic.service.ts (PBKDF2-SHA256 -> AES-256-CBC -> HMAC-SHA256,
    // "v2:" + base64(salt|iv|hmac|ciphertext)) directly against crypto-js
    // with fixed inputs. If this test ever fails after a refactor, the
    // wire format has changed and existing encrypted user data would no
    // longer decrypt — treat that as a hard stop per docs/adr/0001.
    const SALT_HEX = '000102030405060708090a0b0c0d0e0f';
    const IV_HEX = '101112131415161718191a1b1c1d1e1f';
    const KEY = 'correct-horse-battery-staple';
    const PLAINTEXT = 'Hello, Money Manager! 42.50 EUR';
    const GOLDEN_CIPHERTEXT =
      'v2:AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh+QgUHkxXd3CwzP5rUGmUF4LwPDtmyrElSWvbQBBTyPFfmfk0/ovvGMExmxLfp83Wxus9wEKaRteFijh20mTOuM';

    it('encrypts to the exact locked ciphertext given fixed salt/iv/key/plaintext', () => {
      const result = encrypt(PLAINTEXT, KEY, { saltHex: SALT_HEX, ivHex: IV_HEX });
      expect(result).toBe(GOLDEN_CIPHERTEXT);
    });

    it('decrypts the locked golden ciphertext back to the original plaintext', () => {
      expect(decrypt(GOLDEN_CIPHERTEXT, KEY)).toBe(PLAINTEXT);
    });

    it('reads the legacy (pre-v2) passphrase format produced by CryptoJS.AES.encrypt(text, passphrase)', () => {
      const legacyKey = 'legacy-passphrase-1234';
      const legacyPlain = 'legacy plaintext value';
      const legacyCiphertext = CryptoJS.AES.encrypt(legacyPlain, legacyKey).toString();

      expect(isV2Ciphertext(legacyCiphertext)).toBe(false);
      expect(decrypt(legacyCiphertext, legacyKey)).toBe(legacyPlain);
    });
  });

  describe('round-trip with random salt/iv (production usage)', () => {
    it('encrypts and decrypts arbitrary text correctly', () => {
      const key = 'a-random-user-key';
      const plaintext = 'Some transaction comment with unicode: café €12.34 日本語';

      const ciphertext = encrypt(plaintext, key);
      expect(isV2Ciphertext(ciphertext)).toBe(true);
      expect(decrypt(ciphertext, key)).toBe(plaintext);
    });

    it('produces a different ciphertext each time (fresh random salt + iv per call)', () => {
      const key = 'same-key';
      const plaintext = 'same plaintext';

      const a = encrypt(plaintext, key);
      const b = encrypt(plaintext, key);

      expect(a).not.toBe(b);
      expect(decrypt(a, key)).toBe(plaintext);
      expect(decrypt(b, key)).toBe(plaintext);
    });

    it('handles empty string plaintext', () => {
      const key = 'k';
      const ciphertext = encrypt('', key);
      expect(decrypt(ciphertext, key)).toBe('');
    });
  });

  describe('failure modes', () => {
    it('throws DecryptionError when the key is wrong (HMAC mismatch)', () => {
      const ciphertext = encrypt('secret', 'right-key');
      expect(() => decrypt(ciphertext, 'wrong-key')).toThrow(DecryptionError);
    });

    it('throws DecryptionError when the ciphertext has been tampered with', () => {
      const ciphertext = encrypt('secret', 'a-key');
      const tampered = ciphertext.slice(0, -4) + 'AAAA';
      expect(() => decrypt(tampered, 'a-key')).toThrow(DecryptionError);
    });

    it('throws DecryptionError on a too-short v2 payload', () => {
      expect(() => decrypt('v2:AAAA', 'any-key')).toThrow(DecryptionError);
    });
  });

  describe('isV2Ciphertext', () => {
    it('identifies v2-prefixed values', () => {
      expect(isV2Ciphertext('v2:abc')).toBe(true);
      expect(isV2Ciphertext('U2FsdGVkX1...')).toBe(false);
      expect(isV2Ciphertext('plain text')).toBe(false);
    });
  });

  describe('isEncryptedValue', () => {
    it('identifies v2 ciphertext', () => {
      expect(isEncryptedValue(encrypt('x', 'k'))).toBe(true);
    });

    it('identifies legacy ciphertext', () => {
      const legacy = CryptoJS.AES.encrypt('x', 'k').toString();
      expect(isEncryptedValue(legacy)).toBe(true);
    });

    it('rejects plain strings, numbers, and other non-ciphertext values', () => {
      expect(isEncryptedValue('amount')).toBe(false);
      expect(isEncryptedValue('42.50')).toBe(false);
      expect(isEncryptedValue(42.5)).toBe(false);
      expect(isEncryptedValue(null)).toBe(false);
      expect(isEncryptedValue(undefined)).toBe(false);
    });
  });

  describe('EncryptionSession', () => {
    it('round-trips multiple values under one session, matching the one-shot API', () => {
      const session = new EncryptionSession('session-key');
      const values = ['Daily -12.50', '@Groceries', 'Splurge -30.00', ''];

      const ciphertexts = values.map((v) => session.encrypt(v));
      ciphertexts.forEach((c, i) => {
        expect(session.decrypt(c)).toBe(values[i]);
      });
    });

    it('produces the exact same golden ciphertext as the one-shot encrypt() when pinned to the same salt/iv', () => {
      const SALT_HEX = '000102030405060708090a0b0c0d0e0f';
      const IV_HEX = '101112131415161718191a1b1c1d1e1f';
      const KEY = 'correct-horse-battery-staple';
      const PLAINTEXT = 'Hello, Money Manager! 42.50 EUR';

      const session = new EncryptionSession(KEY);
      const viaSession = session.encrypt(PLAINTEXT, { saltHex: SALT_HEX, ivHex: IV_HEX });
      const viaOneShot = encrypt(PLAINTEXT, KEY, { saltHex: SALT_HEX, ivHex: IV_HEX });

      expect(viaSession).toBe(viaOneShot);
    });

    it('reuses the derived key across calls sharing a pinned salt (session-salt pattern)', () => {
      const session = new EncryptionSession('shared-key');
      const saltHex = 'aabbccddeeff00112233445566778899';

      const a = session.encrypt('field one', { saltHex });
      const b = session.encrypt('field two', { saltHex });

      // Different IVs (random per value) -> different ciphertexts, but both
      // decrypt correctly and both embed the same salt.
      expect(a).not.toBe(b);
      expect(session.decrypt(a)).toBe('field one');
      expect(session.decrypt(b)).toBe('field two');
    });

    it('reads legacy-format values through the session too', () => {
      const key = 'legacy-key';
      const legacyCiphertext = CryptoJS.AES.encrypt('legacy value', key).toString();
      const session = new EncryptionSession(key);

      expect(session.decrypt(legacyCiphertext)).toBe('legacy value');
    });

    it('throws DecryptionError on tamper, same as the one-shot API', () => {
      const session = new EncryptionSession('a-key');
      const ciphertext = session.encrypt('secret');
      const tampered = ciphertext.slice(0, -4) + 'AAAA';

      expect(() => session.decrypt(tampered)).toThrow(DecryptionError);
    });
  });
});
