import type { CashflowDoodadCard } from './types';

/**
 * The red "Schnickschnack" pile (Doodads): you buy something you did not plan on, you pay, and that is
 * all - nothing is owned afterwards. Each card also carries a suggested account (a big treat is a
 * Smile, small stuff a Splurge - never Daily or Fire) and a spending group whose translated name
 * becomes the transaction's category (JFK, 2026-10-03).
 */
export const CLASSIC_DOODAD: CashflowDoodadCard[] = [
  {
    id: 'classic-doodad-jetski',
    title: 'Du kaufst einen Jet Ski',
    costMinor: 300000,
    account: 'Smile',
    group: 'leisure',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-reunion',
    title: 'Du gehst zum Klassentreffen',
    costMinor: 50000,
    account: 'Splurge',
    group: 'events',
  },
  {
    id: 'classic-doodad-boat',
    title: 'Du kaufst ein Boot',
    costMinor: 500000,
    account: 'Smile',
    group: 'leisure',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-gym',
    title: 'Du richtest dir einen Fitnessraum ein',
    costMinor: 300000,
    account: 'Smile',
    group: 'wellness',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-chair',
    title: 'Du kaufst einen bequemen Stuhl',
    costMinor: 50000,
    account: 'Splurge',
    group: 'home',
  },
  {
    id: 'classic-doodad-massagesuit',
    title: 'Du gönnst dir einen Massanzug',
    costMinor: 100000,
    account: 'Smile',
    group: 'wellness',
  },
  {
    id: 'classic-doodad-jewelry',
    title: 'Du kaufst Modeschmuck',
    costMinor: 40000,
    account: 'Splurge',
    group: 'style',
  },
  {
    id: 'classic-doodad-cappuccino',
    title: 'Du kaufst eine Cappuccino Maschine',
    costMinor: 30000,
    account: 'Splurge',
    group: 'home',
  },
  {
    id: 'classic-doodad-birthday',
    title: 'Du gibst eine Geburtstagsparty für dein Kind',
    costMinor: 50000,
    account: 'Splurge',
    group: 'events',
    hint: 'child',
  },
  {
    id: 'classic-doodad-kitchen',
    title: 'Du renovierst deine Küche',
    costMinor: 750000,
    account: 'Smile',
    group: 'home',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-tennis',
    title: 'Du kaufst einen neuen Tennisschläger',
    costMinor: 20000,
    account: 'Splurge',
    group: 'leisure',
  },
  {
    id: 'classic-doodad-concert',
    title: 'Du kaufst Konzerttickets',
    costMinor: 20000,
    account: 'Splurge',
    group: 'events',
  },
  {
    id: 'classic-doodad-familyvacation',
    title: 'Ihr macht einen Familienurlaub',
    costMinor: 250000,
    account: 'Smile',
    group: 'leisure',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-sunglasses',
    title: 'Du kaufst eine neue Sonnenbrille',
    costMinor: 20000,
    account: 'Splurge',
    group: 'style',
  },
  {
    id: 'classic-doodad-console',
    title: 'Du kaufst eine neue Spielekonsole',
    costMinor: 60000,
    account: 'Splurge',
    group: 'leisure',
  },
  {
    id: 'classic-doodad-trainingwear',
    title: 'Du brauchst neue Trainingskleidung',
    costMinor: 30000,
    account: 'Splurge',
    group: 'style',
  },
  {
    id: 'classic-doodad-painting',
    title: 'Dein Haus braucht einen neuen Anstrich',
    costMinor: 60000,
    account: 'Splurge',
    group: 'home',
  },
  {
    id: 'classic-doodad-wedding',
    title: 'Unterstütze die Hochzeit deines Kindes',
    costMinor: 200000,
    account: 'Smile',
    group: 'events',
    hint: 'loanChild',
  },
  {
    id: 'classic-doodad-soundsystem',
    title: 'Du kaufst ein neues Soundsystem',
    costMinor: 150000,
    account: 'Smile',
    group: 'home',
  },
  {
    id: 'classic-doodad-bowlingball',
    title: 'Du kaufst eine neue Bowlingkugel',
    costMinor: 10000,
    account: 'Splurge',
    group: 'leisure',
  },
  {
    id: 'classic-doodad-clothes',
    title: 'Du kaufst neue Kleidung',
    costMinor: 100000,
    account: 'Splurge',
    group: 'style',
  },
  {
    id: 'classic-doodad-caraircon',
    title: 'Du brauchst eine neue Klimaanlage für dein Auto',
    costMinor: 70000,
    account: 'Splurge',
    group: 'car',
  },
  {
    id: 'classic-doodad-golfclub',
    title: 'Du wirst Mitglied im Golfclub',
    costMinor: 200000,
    account: 'Smile',
    group: 'leisure',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-watch',
    title: 'Du kaufst eine neue Uhr',
    costMinor: 20000,
    account: 'Splurge',
    group: 'style',
  },
  {
    id: 'classic-doodad-carradio',
    title: 'Du brauchst ein neues Autoradio',
    costMinor: 70000,
    account: 'Splurge',
    group: 'car',
  },
  {
    id: 'classic-doodad-tv',
    title: 'Du kaufst einen Flachbildfernseher',
    costMinor: 250000,
    account: 'Smile',
    group: 'tech',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-firstcar',
    title: 'Du kaufst deinem Kind sein erstes Auto',
    costMinor: 500000,
    account: 'Smile',
    group: 'car',
    hint: 'loanChild',
  },
  {
    id: 'classic-doodad-braces',
    title: 'Dein Kind benötigt eine Zahnspange',
    costMinor: 400000,
    account: 'Smile',
    group: 'wellness',
    hint: 'loanChild',
  },
  {
    id: 'classic-doodad-date',
    title: 'Du hast ein Date (Konzert, Essen & Dessert!)',
    costMinor: 50000,
    account: 'Splurge',
    group: 'events',
  },
  {
    id: 'classic-doodad-rims',
    title: 'Dein Auto braucht neue Felgen',
    costMinor: 200000,
    account: 'Smile',
    group: 'car',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-foodprocessor',
    title: 'Du kaufst eine Küchenmaschine',
    costMinor: 20000,
    account: 'Splurge',
    group: 'home',
  },
  {
    id: 'classic-doodad-golfclubs',
    title: 'Du gönnst dir neue Golfschläger',
    costMinor: 80000,
    account: 'Splurge',
    group: 'leisure',
  },
  {
    id: 'classic-doodad-tutoring',
    title: 'Du zahlst Privatunterricht für dein Kind',
    costMinor: 50000,
    account: 'Splurge',
    group: 'education',
    hint: 'child',
  },
  {
    id: 'classic-doodad-computer',
    title: 'Du brauchst einen neuen Computer',
    costMinor: 180000,
    account: 'Smile',
    group: 'tech',
    hint: 'loan',
  },
  {
    id: 'classic-doodad-seasontickets',
    title: 'Du kaufst Saison Tickets',
    costMinor: 150000,
    account: 'Smile',
    group: 'events',
  },
  {
    id: 'classic-doodad-tires',
    title: 'Du brauchst neue Reifen',
    costMinor: 60000,
    account: 'Splurge',
    group: 'car',
  },
  {
    id: 'classic-doodad-dentist',
    title: 'Geh zum Zahnarzt',
    costMinor: 70000,
    account: 'Smile',
    group: 'wellness',
  },
  {
    id: 'classic-doodad-casino',
    title: 'Du gehst ins Casino',
    costMinor: 80000,
    account: 'Splurge',
    group: 'leisure',
  },
  {
    id: 'classic-doodad-winetrip',
    title: 'Du machst einen Ausflug in ein Weinanbaugebiet',
    costMinor: 100000,
    account: 'Smile',
    group: 'leisure',
  },
  {
    id: 'classic-doodad-artpainting',
    title: 'Du kaufst ein Gemälde eines lokalen Künstlers',
    costMinor: 80000,
    account: 'Smile',
    group: 'home',
  },
  {
    id: 'classic-doodad-friendsdinner',
    title: 'Du lädst deine Freunde zum Abendessen ein',
    costMinor: 20000,
    account: 'Splurge',
    group: 'events',
  },
  {
    id: 'classic-doodad-phone',
    title: 'Du kaufst dir das neuste Handy',
    costMinor: 30000,
    account: 'Splurge',
    group: 'tech',
  },
];
