/**
 * The Cashflow manual as Markdown (JFK, 2026-10-08): the manual lives as data per language
 * (`src/assets/i18n/cashflow-manual/<lang>.json`, drawn by the app), and an agent that teaches the game reads the same
 * text - in the language it is asked to teach in - through `explain_concept` (topics `cashflow_manual_<lang>`). One
 * function renders it, a spec keeps `docs/domain/CASHFLOW_MANUAL_<LANG>.md` equal to it, and a change to the manual
 * therefore cannot leave the agent teaching an older version.
 */

type Block = { type: string; [key: string]: unknown };

export interface ManualJson {
  title: string;
  subtitle: string;
  sections: Record<string, { title: string; intro?: string; blocks: Block[] }>;
}

const cell = (value: unknown): string =>
  String(value ?? '')
    .replace(/\|/g, '/')
    .replace(/\s+/g, ' ')
    .trim();

function renderBlock(block: Block): string[] {
  const text = (key: string): string => String(block[key] ?? '');
  switch (block.type) {
    case 'p':
      return [text('text'), ''];
    case 'h3':
      return [`### ${text('text')}`, ''];
    case 'list': {
      const items = (block['items'] as string[]) ?? [];
      return [
        ...items.map((item, index) => (block['ordered'] ? `${index + 1}. ${item}` : `- ${item}`)),
        '',
      ];
    }
    case 'callout': {
      const title = text('title');
      return [`> ${title ? `**${title}** ` : ''}${text('text')}`, ''];
    }
    case 'steps':
      return [
        ...((block['items'] as { title: string; text: string }[]) ?? []).map(
          (item, index) => `${index + 1}. **${item.title}** - ${item.text}`,
        ),
        '',
      ];
    case 'cards':
      return [
        ...((block['items'] as { title: string; text: string }[]) ?? []).map(
          (item) => `- **${item.title}** - ${item.text}`,
        ),
        '',
      ];
    case 'glossary':
      return [
        ...((block['items'] as { term: string; text: string }[]) ?? []).map(
          (item) => `- **${item.term}**: ${item.text}`,
        ),
        '',
      ];
    case 'table': {
      const head = ((block['head'] as string[]) ?? []).map(cell);
      const rows = (block['rows'] as string[][]) ?? [];
      const lines = [
        `| ${head.join(' | ')} |`,
        `| ${head.map(() => '---').join(' | ')} |`,
        ...rows.map((row) => `| ${row.map(cell).join(' | ')} |`),
      ];
      if (block['note']) lines.push('', `_${text('note')}_`);
      return [...lines, ''];
    }
    case 'data':
      // computed from the card catalog when the page is drawn: the agent reads the numbers from the card topics
      return [
        `_(Table: ${text('caption') || text('id')} - the figures are in the topics cashflow_cards, cashflow_card_lab and cashflow_strategy_lab.)_`,
        '',
      ];
    case 'face':
      return [
        `_(Example card: ${text('cardId')}${block['caption'] ? ` - ${text('caption')}` : ''}; see cashflow_cards.)_`,
        '',
      ];
    case 'cardbrowser':
      return ['_(Every card with its id: topic cashflow_cards.)_', ''];
    default:
      return [];
  }
}

/** The whole manual of one language as a Markdown document. */
export function renderManualMarkdown(manual: ManualJson, language: string): string {
  const lines: string[] = [
    `# ${manual.title}`,
    '',
    `<!-- Generated by scripts/manual-markdown.js from src/assets/i18n/cashflow-manual/${language}.json - do not edit by hand. -->`,
    '',
    manual.subtitle,
    '',
  ];
  Object.values(manual.sections).forEach((section, index) => {
    lines.push(`## ${index + 1}. ${section.title}`, '');
    if (section.intro) lines.push(section.intro, '');
    for (const block of section.blocks) lines.push(...renderBlock(block));
  });
  return (
    lines
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  );
}

/** The languages the manual is written in (the app's six). */
export const MANUAL_MARKDOWN_LANGUAGES = ['en', 'de', 'es', 'fr', 'cn', 'ar'] as const;
